ublox_gps_node:
  ros__parameters:
    dynamic_model: automotive
         # Airborne < 2G, 2D fix not supported (3D only),

    debug: 0
    set_baudrate: false
    device: /dev/ttyACM0 # smc_plus device name
    frame_id: gps
    uart1:
      baudrate: 115200
      in: 35
      out: 35
    rate: 10.0
    # TMODE3 Config
    tmode3: 0
    inf:
      all: true
    publish:
      all: true
      aid:
        hui: false
      nav:
        posecef: false
        relposned: True
    gnss:
      sbas: True
      galileo: True
      beidou: True
      qzss: True
      glonass: True